Configurations:
  - DscLcmController
  #- DscLcmMaintenanceWindows
  - DscTagging
# This seems to be causing a problem during JeaSession...
#  - DscDiagnostic

# This must be here, but must not be listed above in "Configurations:"
LcmConfig:
  Settings:
    RefreshMode: Push
    RefreshFrequencyMins: 30
    RebootNodeIfNeeded: true
    ActionAfterReboot: ContinueConfiguration
    AllowModuleOverwrite: true
    #CertificateID: ...
    ConfigurationMode: ApplyAndMonitor
    ConfigurationModeFrequencyMins: 30
    DebugMode: All
  # When we move into Pull Mode configuration instead of Push, we'll have to fill in non-dummy values here
  # What do these do? They're required, yet throw a warning if RefreshMode is set to Push above - 1/26/21
  # WARNING: A ConfigurationRepository is specified without setting the refresh mode into PULL.
  #ConfigurationRepositoryWeb:
  #  Server:
  #    ServerURL: https://dscpull01.contoso.com:8080/PSDSCPullServer.svc
  #    RegistrationKey: ec717ee9-b343-49ee-98a2-26e53939eecf
  #ReportServerWeb:
  #    ServerURL: https://dscpull01.contoso.com:8080/PSDSCPullServer.svc
  #    RegistrationKey: ec717ee9-b343-49ee-98a2-26e53939eecf

# Default
DscTagging:
  Version: 0.3.0

# Don't apply DSC configuration during this time
DscLcmMaintenanceWindows:
  MaintenanceWindows:
#    - Name: Always
#      StartTime: 00:00:00
#      Timespan: 24:00:00
    - Name: KWFirstWednesdayNight
      DayOfWeek: Wednesday
      StartTime: 00:30:00
      Timespan: 02:00:00
    #  On: 1st
    #- Name: SundayAllDay
    #  DayOfWeek: Sunday
    #  StartTime: 00:00:00
    #  Timespan: 24:00:00

# Set values for Local Configuration Manager on target servers
DscLcmController:
  MaintenanceWindowMode: Monitor # or Monitor. In Monitor mode the LCM won't do changes in maintenance window.
#  MaintenanceWindowMode: AutoCorrect # or Monitor. In Monitor mode the LCM won't do changes in maintenance window.
  MonitorInterval: 00:15:00          #
  AutoCorrectInterval: 00:15:00      #
#  AutoCorrectInterval: 00:30:00      #
  AutoCorrectIntervalOverride: false #   THESE VALUES ARE VERY LOW FOR EASY TESTING AND DEMONSTRATIONS
  RefreshInterval: 00:30:00          #
  RefreshIntervalOverride: false     #   PLEASE INCREASE THE VALUES TO PREVENT OVERLOADING THE PULL SERVER
  ControllerInterval: 00:05:00       #   AS WELL AS THE NODES. ALSO THE SQL DATABASE GROWS PRETTY FAST IF A
  MaintenanceWindowOverride: false   #   REPORT IS SENT EVERY 5 MINUTES.
  WriteTranscripts: true             #
  SendDscTaggingData: true           #
  MaxLcmRuntime: 00:30:00            #
