Configurations:
  #- FilesAndFolders
  #- SecurityBase
  - WindowsFeatures

WindowsFeatures:
  Name:
    - File-Services
    - FS-Resource-Manager
    - RSAT-FSRM-Mgmt
    - FS-Data-Deduplication

# FilesAndFolders:
#   Items:
#     - DestinationPath: C:\Test
#       Type: Directory
#     - DestinationPath: C:\Test\Test1File1.txt
#       Type: File
#       Contents: Some test data
#       DependsOn: '[File]C\Test'
#     - DestinationPath: C:\Test\Test1File2.txt
#       Type: File
#       Contents: Some test data
#       DependsOn: '[File]C\Test'
#     - DestinationPath: C:\GpoBackup
#       SourcePath: \\DSCDC01\SYSVOL\contoso.com\Policies
#       Type: Directory

#SecurityBase:
#  Role: Baseline

  #Role: FileServer

  # The parameter under Disks must match, by name, what's in Disks.schema.psm1
  # Renaming from DiskLayout to Disks worked!
  # Use what git pulls for Disks.schema.psm1, but then use "Disks" (instead of what's in the online tutorial) for the
  #  input parameter to Disks, the configuration script
# Disks:
#   Disks:
#     - DiskId: 0
#       DiskIdType: Number
#       DriveLetter: C
#       FSLabel: System
#     - DiskId: 1
#       DiskIdType: Number
#       DriveLetter: D
#       FSLabel: Data
