Configurations:
  - FilesAndFolders
  - Scripts

FilesAndFolders:
  Items:
    - SourcePath: \\v26267ncsp502\ORDchoco\FilesToCopy\BootHole
      DestinationPath: C:\BootHole
      Type: Directory
      # Recurse has to be specified as true, not $true or Enabled, or it will blow up
      Recurse: true

Scripts:
  Items:
    - Name: FixBootHole
      # Successful run of _BootHole will create signature.p7
      # If we don't Chdir \BootHole, the current dir will be \windows\system32, and the .ps1 files inside the .cmd won't be found in that folder
      GetScript: |
        test-path C:\BootHole\signature.p7
      TestScript: |
        [scriptblock]::Create($GetScript).Invoke()
      SetScript: |
        Chdir \BootHole
        C:\BootHole\_BootHole.cmd
