Configurations:
  - FirewallRules
  - RegistryValues
  - WindowsFeatures

WindowsFeatures:
  Name:
    #- File-Services
    #- FS-FileServer
    - BranchCache
    #- Multipath-IO # ? How does Leigh want this configured?
    #- FS-NFS-Service
    - RSAT-Feature-Tools-BitLocker
    - RSAT-Feature-Tools-BitLocker-RemoteAdminTool
    - RSAT-ADDS-Tools
    - RSAT-Feature-Tools-BitLocker-BdeAducExt # Depends on RSAT-ADDS-Tools
    - RSAT-SNMP
    - RSAT-AD-Tools # This forces RSAT-AD-PowerShell, RSAT-ADDS, RSAT-ADLDS - according to DSC
    - RSAT-ADDS # This forces RSAT-AD-AdminCenter, which we were then trying to remove later
    - System-DataArchiver
    #- Windows-Defender # Currently installed
    - -NFS-Client
    - -Server-Media-Foundation
    # This seems to cause problems when we try to remove it after installing RSAT-AD-Tools
    #- -RSAT-AD-PowerShell # Depends on PowerShell, NET-Framework-45-Core - Why is this still installed when I've tried to remove it?
    #- -RSAT-AD-AdminCenter # Depends on RSAT-AD-PowerShell, RSAT-ADDS-Tools, NET-Framework-45-Core
    #- -RSAT-RDS-Tools - Temporary comment
    #- -UpdateServices-RSAT - Temporary comment
    - -UpdateServices-API # Depends on NET-Framework-45-Core
    - -UpdateServices-UI # Depends on UpdateServices-API
    - -WDS-AdminPack
    #- -Windows-Defender-Features # Doesn't even exist when I query 2019 server
    #- -Windows-Defender-Gui # Doesn't even exist when I query 2019 server
    - -Windows-Server-Backup

RegistryValues:
  Values:
    - Key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters
      ValueName: MaxNegativeCacheTtl
      ValueData: 0
      ValueType: DWord
      Ensure: Present
      Force: true
    - Key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NetLogon\Parameters
      ValueName: NegativeCachePeriod
      ValueData: 0
      ValueType: DWord
      Ensure: Present
      Force: true
    - Key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters
      ValueName: AlwaysExpectDomainController
      ValueData: 1
      ValueType: DWord
      Ensure: Present
      Force: true

FirewallRules:
  Rules:
    - Name: CustomRemoteConsoleAccessFromAnotherServer
      DisplayName: Remote console access from another server
      Enabled: True
      #Description: Allow All Inbound Trafic
      Direction: Inbound
      Profile: Any
      Action: Allow
      LocalPort: 6547
      RemotePort: 6547
      Protocol: TCP
    - Name: CustomUPSToCommunicateToPCNS
      DisplayName: UPS to communicate to PCNS
      Enabled: True
      #Description: Allow All Inbound Trafic
      Direction: Inbound
      Profile: Any
      Action: Allow
      LocalPort: 3052
      RemotePort: 3052
      Protocol: UDP
