Configurations:
  - FirewallRules
  # Below is from HardwareServer
  #- FilesAndFolders
  - RegistryValues
  #- Scripts

RegistryValues:
  Values:
    - Key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters
      ValueName: MaxNegativeCacheTtl
      ValueData: 0
      ValueType: DWord
      Ensure: Present
      Force: true
    - Key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NetLogon\Parameters
      ValueName: NegativeCachePeriod
      ValueData: 0
      ValueType: DWord
      Ensure: Present
      Force: true
    - Key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters
      ValueName: AlwaysExpectDomainController
      ValueData: 1
      ValueType: DWord
      Ensure: Present
      Force: true

# FilesAndFolders:
#   Items:
#     - DestinationPath: C:\BootHole
#       SourcePath: \\v26267ncsp502\ORDchoco\FilesToCopy\BootHole
#       Type: Directory
#       # Recurse has to be specified as true, not $true or Enabled, or it will blow up
#       Recurse: true

# Scripts:
#   Items:
#     - Name: FixBootHole
#       # Successful run of _BootHole will create signature.p7
#       # If we don't Chdir \BootHole, the current dir will be \windows\system32, and the .ps1 files inside the .cmd won't be found in that folder
#       GetScript: |
#         $Result = test-path C:\BootHole\signature.p7
#         Return @{ Result = $Result}
#       TestScript: |
#         $ReturnHash = [scriptblock]::Create($GetScript).Invoke()
#         $ReturnHash.Result
#       SetScript: |
#         Chdir \BootHole
#         C:\BootHole\_BootHole.cmd

FirewallRules:
  Rules:
    - Name: CustomRemoteConsoleAccessFromAnotherServer
      DisplayName: Remote console access from another server
      Enabled: True
      #Description: Allow All Inbound Trafic
      Direction: Inbound
      Profile: Any
      Action: Allow
      LocalPort: 6547
      RemotePort: 6547
      Protocol: TCP
    - Name: CustomUPSToCommunicateToPCNS
      DisplayName: UPS to communicate to PCNS
      Enabled: True
      #Description: Allow All Inbound Trafic
      Direction: Inbound
      Profile: Any
      Action: Allow
      LocalPort: 3052
      RemotePort: 3052
      Protocol: UDP
