Configurations:
  - SecurityBase
  - WindowsFeatures
  #- DSC_IPAddress
  #- NetIPInterface
  #- IpConfiguration
  - ChocolateyPackages
  #- Scripts
  #- ORDNewIPAdapter
  #- InstallIPv4OnBareMetal
#  - RegistryValues
  #- NetworkIpConfiguration
  #- Interfaces
  #- MSFT_xIPAddress

ORDNewIPAdapter:
  IPAddress: '172.16.2.140'
  InterfaceAlias: "Ethernet1"
  Ensure: Present

# DSC_IPAddress:
#   IPAddress: 172.16.2.140
#   InterfaceAlias: "Ethernet1"
#   AddressFamily: 'IPV4'

# Scripts:
#   Items:
#     - Name: FixIPv6DHCP
#       GetScript: |
#         Result = "@(Get-NetIPInterface -AddressFamily 'IPv6' | Where-Object {$_.DHCP -ne 'disabled'})"
#       TestScript: |
#         $Found = [scriptblock]::Create($GetScript).Invoke()
#         $Found.count -eq 0
#       SetScript: |
#         Get-NetIPInterface -AddressFamily 'IPv6'
#     - Name: InstallIPv4OnBareMetal
#       GetScript:
#       TestScript:
#       SetScript:
      #MyParm:

  #Set-NetIPInterface -AddressFamily IPv6 -Dhcp Disabled
        #Set-NetIPInterface -AddressFamily IPv6 -RouterDiscovery Disabled
# Don't use double quotes below, use only single quotes
# Scripts:
#   Items:
#     - Name: InstallIPv4OnBareMetal
#       GetScript:
#       TestScript:
#       SetScript:

# This does not need to be done as an array, even though it will take an array
ChocolateyPackages:
  Software:
    Ensure: Present
  Features:
    Name: useFipsCompliantChecksums
    Ensure: Present
  Sources:
    Name: ORDChoco
    Ensure: Present
    Source: '\\V26265NCHH500\ORDChoco'
  Packages:
    - Name: sccm
      Ensure: Present
      ChocolateyOptions:
        Source: ORDChoco
    - Name: encase
      Ensure: Present
      ChocolateyOptions:
        Source: ORDChoco
    - Name: bigfix
      Ensure: Present
      ChocolateyOptions:
        Source: ORDChoco
    - Name: laps
      Ensure: Present
      ChocolateyOptions:
        Source: ORDChoco

# NetworkIpConfiguration:
#   Interfaces:
#     - InterfaceAlias: Ethernet1
#       IpAddress: 172.16.2.88
#       Prefix: 24
#       Gateway: 172.16.2.1
#       DnsServer: 134.67.208.5
#       DisableNetbios: true
#     # - InterfaceAlias: Production
#     #   IpAddress: 134.67.216.88
#     #   Prefix: 24
#     #   Gateway: 134.67.216.1
#     #   DnsServer: 161.80.76.28

WindowsFeatures:
  Name:
    - -Telnet-Client

SecurityBase:
  Role: Baseline

# IpConfiguration:
#   Adapter:
#     - NewName: Production
#       AddressFamily: IPv4
#       GatewayAddress: 192.168.111.51
#       DnsServerAddress:
#         - 134.67.208.5
#         - 161.80.76.28
#       #DisableIpv6: true
#     - NewName: Ethernet1
#       AddressFamily: IPv4
#       GatewayAddress: 192.168.111.51
#       DnsServerAddress:
#         - 134.67.208.5
#         - 161.80.76.28
#       #DisableIpv6: true

# Interfaces:
#   - NetworkIpConfiguration:
#     - InterfaceAlias: Ethernet1
#       IpAddress: 172.16.2.141
#       Prefix: 24
#       Gateway: 172.16.2.1
#       DnsServer: 134.67.208.5
#       DisableNetbios: true
#   - NetworkIpConfiguration:
#     - InterfaceAlias: Production
#       IpAddress: 134.67.216.199
#       Prefix: 24
#       Gateway: 134.67.216.1
#       DnsServer: 161.80.76.28

#      DnsServer:
#        - 134.67.208.5
#        - 161.80.76.28

#NetworkIpConfiguration:
#  IPAddress: 192.168.0.11
#  Prefix: 24
#  Gateway: 192.168.0.1
#  DnsServer: ['134.67.208.5', '161.80.76.28']
#  InterfaceAlias: Ethernet1
#  DisableNetbios: True

RegistryValues:
  Values:
    - Key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Parameters
      ValueName: NtpServer
      ValueData: pool.ntp.org,0x9
      ValueType: String
      Ensure: Present
      Force: true
