Configurations:
  - SecurityBase
  #- SoftwareBaseline
  - WindowsFeatures
  - NetworkIpConfiguration
  #- ChocolateyFeature
  #- Chocolatey
  #- ChocolateyPackages
  #- RegistryValues
#  - ChocoFeature
#  - cChoco

ChocolateyFeature:
  Name: useFipsCompliantChecksums
  Ensure: Present  # Enabled

#cChoco:
#  Name: useFipsCompliantChecksums
#  Ensure: Present


#SoftwareBaseline: # Parameters for DSC Composite Configuration SoftwareBaseline

#Software: # Parameters for DSC Composite Configuration Software?
#  Sources:
#    - Name: chocolatey
#      Disabled: false
#      Source: https://chocolatey.org/api/v2

#  Packages:
#    - Name: chocolatey

#    - Name: NotepadPlusplus
#      Version: '7.5.2'
#    - Name: Putty

NetworkIpConfiguration:
  Prefix: 24
  Gateway: 192.168.111.51
  DnsServer: ['134.67.208.5', '161.80.76.28']
  InterfaceAlias: Production
  #InterfaceAlias: Ethernet
  DisableNetbios: True

Chocolatey:
  Ensure: Present
  ChocolateyFeature:
    Name: useFipsCompliantChecksums
    Ensure: Present

    # Enabled
  #Feature: xyz
  #xyz: abc

#cChocoInstaller installChoco
#{
#  InstallDir = "c:\choco"
#  DependsOn = "[WindowsFeature]NetFrameworkCore"
#}

ChocolateyPackages:
  Software:
    Ensure: Present
  #Sources:
    #- Name: Chocolatey
    #  Ensure: Present

    #- Name: PrivateChocolatey
    #  Ensure: Present
    #  Source: \\v26265nchh500\chiz$\software installs and downloads\ChocolateyPackages

    #ChocolateyFeature: useFipsCompliantChecksums
  #ChocolateyFeature:
  #  Name: useFipsCompliantChecksums
  #  Ensure: Present  # Enabled
  Packages:
  #- Name: microsoft-monitoring-agent
  #  Ensure: Present
    - Name: sccm
      Ensure: Present
      ChocolateyOptions:
#        Source: Software # We need to get the package to the other side
        Source: ORDChoco # We need to get the package to the other side
    - Name: winrar
      Ensure: Present
    #Version: '5.90.0.20200401'
    #Credential: '[ENC=PE9ianMgVmVyc2lvbj0iMS4xLjAuMSIgeG1sbnM9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vcG93ZXJzaGVsbC8yMDA0LzA0Ij4NCiAgPE9iaiBSZWZJZD0iMCI+DQogICAgPFROIFJlZklkPSIwIj4NCiAgICAgIDxUPlN5c3RlbS5NYW5hZ2VtZW50LkF1dG9tYXRpb24uUFNDdXN0b21PYmplY3Q8L1Q+DQogICAgICA8VD5TeXN0ZW0uT2JqZWN0PC9UPg0KICAgIDwvVE4+DQogICAgPE1TPg0KICAgICAgPE9iaiBOPSJLZXlEYXRhIiBSZWZJZD0iMSI+DQogICAgICAgIDxUTiBSZWZJZD0iMSI+DQogICAgICAgICAgPFQ+U3lzdGVtLk9iamVjdFtdPC9UPg0KICAgICAgICAgIDxUPlN5c3RlbS5BcnJheTwvVD4NCiAgICAgICAgICA8VD5TeXN0ZW0uT2JqZWN0PC9UPg0KICAgICAgICA8L1ROPg0KICAgICAgICA8TFNUPg0KICAgICAgICAgIDxPYmogUmVmSWQ9IjIiPg0KICAgICAgICAgICAgPFROUmVmIFJlZklkPSIwIiAvPg0KICAgICAgICAgICAgPE1TPg0KICAgICAgICAgICAgICA8UyBOPSJIYXNoIj5ENzE4MTg4OTJEOTIxNjMwMzM4MkFEQkE3NEFEOTFFOTVDOTU4RjdGQTEyQ0Q4MEJGMEQzN0NDQUZCREE5MTE2PC9TPg0KICAgICAgICAgICAgICA8STMyIE49Ikl0ZXJhdGlvbkNvdW50Ij41MDAwMDwvSTMyPg0KICAgICAgICAgICAgICA8QkEgTj0iS2V5Ij5iSWxFbGd4RTlYaER6N3gxT3Qya2RLT2ZDWkM2RFNxRlVpREtDUVBPYmJCYTlaY1l6TXI2dGRKcHZwRE5vTU5nPC9CQT4NCiAgICAgICAgICAgICAgPEJBIE49Ikhhc2hTYWx0Ij5EU1BYVm1jSklkbGFHMnRrQ2xrUlBvSW45cmhGOEZtVzZFVTN5eTRtRFhrPTwvQkE+DQogICAgICAgICAgICAgIDxCQSBOPSJTYWx0Ij5HUUluU2J1OThQaUZwMmNMeWdDeW0zeXRYYVZQMlVhdkNqQjhPcHlNTEJJPTwvQkE+DQogICAgICAgICAgICAgIDxCQSBOPSJJViI+YmV5b0ZOeVpRQzV1R3lMZ1dQZmhsZ0tScEJyL204bHFWc3UrMUdkaTNFZz08L0JBPg0KICAgICAgICAgICAgPC9NUz4NCiAgICAgICAgICA8L09iaj4NCiAgICAgICAgPC9MU1Q+DQogICAgICA8L09iaj4NCiAgICAgIDxCQSBOPSJDaXBoZXJUZXh0Ij54dy90WGh0UFp3MEF6anlmL1JkRW1QYVg1ZUNDWS9hS3pqQmwzd0dHck14K2pIT0VpVXpORGdjdk9ScGd4Q1FuTWMzQ1g5dnlNWlhPWmNXVjRjOWZ2UT09PC9CQT4NCiAgICAgIDxCQSBOPSJITUFDIj5uK1lYS0ZQdzU1Q3orN0F0cWRrQUpIUUxQTjdYaEE3K2k4V3k2ZDg1OTBFPTwvQkE+DQogICAgICA8UyBOPSJUeXBlIj5TeXN0ZW0uTWFuYWdlbWVudC5BdXRvbWF0aW9uLlBTQ3JlZGVudGlhbDwvUz4NCiAgICA8L01TPg0KICA8L09iaj4NCjwvT2Jqcz4=]'
    # The package was not found with the source listed:
    #ChocolateyOptions:
    #  Source: Software

# ChocolateyPackages:
#   Software:
#     Ensure: Present
#     PackageFeedUrl: 'https://chocolatey.org/api/v2'
#   Packages:
#   - Name: microsoft-monitoring-agent
#     Ensure: Present
#     ChocolateyOptions:
#       Source: 'https://chocolatey.org/api/v2'

# ChocolateyPackages:
# # I mistakenly munged this to say "Package", when it must be "Packages".
#   Software:
#     Ensure: Present
#     PackageFeedUrl: 'https://chocolatey.org/api/v2'
#     #Version: 'Latest'
#   Packages:
#   - Name: microsoft-monitoring-agent
#     Ensure: Present
#     #Version: 'Latest'
#     # Added 4:22 - blows up
#     #PackageFeedUrl: 'https://chocolatey.org/api/v2'
#     #Version: '10.20.18053.0'
#     #Credential: '[ENC=<LongStringHere>]'
#     # With this commented out, and latest versions, I get: Cannot bind argument to parameter 'Path' because it is null.
#     ChocolateyOptions:
#       Source: 'https://chocolatey.org/api/v2'
#       #Source: Software

# This, or very like it, ensured we got the choco install into the target's c:\programdata\chocolatey, but not farther
# ChocolateyPackages:
# # I munged this to say "Package", when it must be "Packages".
#   Software:
#     Ensure: Present
#     PackageFeedUrl: 'https://chocolatey.org/api/v2'
#     Version: 'Latest'
#   Packages:
#   - Name: microsoft-monitoring-agent
#     Ensure: Present
#     Version: 'Latest'
#     #Version: '10.20.18053.0'
#     #Credential: '[ENC=<LongStringHere>]'
#     ChocolateyOptions:
#       Source: Software

  # %WinDir%\System32\msiexec.exe /i path\Directory\MOMAgent.msi /qn USE_SETTINGS_FROM_AD=1 USE_MANUALLY_SPECIFIED_SETTINGS=0 MANAGEMENT_GROUP=EPAORDSCOM MANAGEMENT_SERVER_DNS=MSname MANAGEMENT_SERVER_AD_NAME=v26267ncsp520 ACTIONS_USE_COMPUTER_ACCOUNT=0 ACTIONSUSER=UserName ACTIONSDOMAIN=DomainName ACTIONSPASSWORD=Password AcceptEndUserLicenseAgreement=1

#ChocolateyPackages:
#  Packages:
#  - Name: winrar
#    Ensure: Present
#    Version: '5.90.0.20200401'
#    Credential: '[ENC=PE9ianMgVmVyc2lvbj0iMS4xLjAuMSIgeG1sbnM9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vcG93ZXJzaGVsbC8yMDA0LzA0Ij4NCiAgPE9iaiBSZWZJZD0iMCI+DQogICAgPFROIFJlZklkPSIwIj4NCiAgICAgIDxUPlN5c3RlbS5NYW5hZ2VtZW50LkF1dG9tYXRpb24uUFNDdXN0b21PYmplY3Q8L1Q+DQogICAgICA8VD5TeXN0ZW0uT2JqZWN0PC9UPg0KICAgIDwvVE4+DQogICAgPE1TPg0KICAgICAgPE9iaiBOPSJLZXlEYXRhIiBSZWZJZD0iMSI+DQogICAgICAgIDxUTiBSZWZJZD0iMSI+DQogICAgICAgICAgPFQ+U3lzdGVtLk9iamVjdFtdPC9UPg0KICAgICAgICAgIDxUPlN5c3RlbS5BcnJheTwvVD4NCiAgICAgICAgICA8VD5TeXN0ZW0uT2JqZWN0PC9UPg0KICAgICAgICA8L1ROPg0KICAgICAgICA8TFNUPg0KICAgICAgICAgIDxPYmogUmVmSWQ9IjIiPg0KICAgICAgICAgICAgPFROUmVmIFJlZklkPSIwIiAvPg0KICAgICAgICAgICAgPE1TPg0KICAgICAgICAgICAgICA8UyBOPSJIYXNoIj5ENzE4MTg4OTJEOTIxNjMwMzM4MkFEQkE3NEFEOTFFOTVDOTU4RjdGQTEyQ0Q4MEJGMEQzN0NDQUZCREE5MTE2PC9TPg0KICAgICAgICAgICAgICA8STMyIE49Ikl0ZXJhdGlvbkNvdW50Ij41MDAwMDwvSTMyPg0KICAgICAgICAgICAgICA8QkEgTj0iS2V5Ij5iSWxFbGd4RTlYaER6N3gxT3Qya2RLT2ZDWkM2RFNxRlVpREtDUVBPYmJCYTlaY1l6TXI2dGRKcHZwRE5vTU5nPC9CQT4NCiAgICAgICAgICAgICAgPEJBIE49Ikhhc2hTYWx0Ij5EU1BYVm1jSklkbGFHMnRrQ2xrUlBvSW45cmhGOEZtVzZFVTN5eTRtRFhrPTwvQkE+DQogICAgICAgICAgICAgIDxCQSBOPSJTYWx0Ij5HUUluU2J1OThQaUZwMmNMeWdDeW0zeXRYYVZQMlVhdkNqQjhPcHlNTEJJPTwvQkE+DQogICAgICAgICAgICAgIDxCQSBOPSJJViI+YmV5b0ZOeVpRQzV1R3lMZ1dQZmhsZ0tScEJyL204bHFWc3UrMUdkaTNFZz08L0JBPg0KICAgICAgICAgICAgPC9NUz4NCiAgICAgICAgICA8L09iaj4NCiAgICAgICAgPC9MU1Q+DQogICAgICA8L09iaj4NCiAgICAgIDxCQSBOPSJDaXBoZXJUZXh0Ij54dy90WGh0UFp3MEF6anlmL1JkRW1QYVg1ZUNDWS9hS3pqQmwzd0dHck14K2pIT0VpVXpORGdjdk9ScGd4Q1FuTWMzQ1g5dnlNWlhPWmNXVjRjOWZ2UT09PC9CQT4NCiAgICAgIDxCQSBOPSJITUFDIj5uK1lYS0ZQdzU1Q3orN0F0cWRrQUpIUUxQTjdYaEE3K2k4V3k2ZDg1OTBFPTwvQkE+DQogICAgICA8UyBOPSJUeXBlIj5TeXN0ZW0uTWFuYWdlbWVudC5BdXRvbWF0aW9uLlBTQ3JlZGVudGlhbDwvUz4NCiAgICA8L01TPg0KICA8L09iaj4NCjwvT2Jqcz4=]'
#    ChocolateyOptions:
#      Source: Software

RegistryValues:
  Values:
    - Key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Parameters
      ValueName: NtpServer
      ValueData: time.windows.com,0x9
      ValueType: String
      Ensure: Present
      # Force must be true to get it to CHANGE an existing value
      Force: true
